from __future__ import annotations


COMMERCIAL_POLICY_SIGNALS: tuple[tuple[tuple[str, ...], int, str], ...] = (
    (
        (
            "bill",
            "billing",
            "invoice",
            "charge",
            "charged",
            "payment",
            "pricing",
            "subscription",
            "plan",
            "账单",
            "计费",
            "收费",
            "扣费",
            "套餐",
            "订阅",
        ),
        2,
        "The email discusses billing, charging, or subscription details.",
    ),
    (
        (
            "refund",
            "refunds",
            "reimburse",
            "credit back",
            "chargeback",
            "退款",
            "退费",
            "退回",
            "撤销扣款",
        ),
        2,
        "The customer explicitly requests a refund or charge reversal.",
    ),
    (
        (
            "sla",
            "compensation",
            "contract",
            "legal",
            "policy",
            "terms",
            "agreement",
            "补偿",
            "合同",
            "法律",
            "条款",
            "政策",
            "承诺边界",
        ),
        2,
        "The request touches SLA, compensation, legal, contract, or policy constraints.",
    ),
    (
        (
            "cancel subscription",
            "cancel my subscription",
            "cancel plan",
            "取消订阅",
            "取消套餐",
            "取消服务",
        ),
        1,
        "The customer asks for cancellation-related account action.",
    ),
)

TECHNICAL_ISSUE_SIGNALS: tuple[tuple[tuple[str, ...], int, str], ...] = (
    (
        (
            "error",
            "errors",
            "failed",
            "failure",
            "failing",
            "bug",
            "issue",
            "broken",
            "not working",
            "doesn't work",
            "cannot",
            "can't",
            "unable",
            "unavailable",
            "timeout",
            "timed out",
            "exception",
            "login failed",
            "报错",
            "失败",
            "异常",
            "无法",
            "不能",
            "不可用",
            "超时",
            "出错",
        ),
        2,
        "The customer reports an operational failure, error, or unavailable behavior.",
    ),
    (
        (
            "tried",
            "i tried",
            "configured",
            "set up",
            "setup",
            "followed the docs",
            "followed your guide",
            "after i",
            "when i",
            "按文档",
            "按照文档",
            "配置了",
            "升级套餐时",
            "我点击",
            "我尝试",
            "我配置",
        ),
        1,
        "The customer describes an attempted action or setup before the failure.",
    ),
)

KNOWLEDGE_REQUEST_QUESTION_KEYWORDS: tuple[str, ...] = (
    "how to",
    "how do i",
    "can i",
    "does it support",
    "do you support",
    "is it possible",
    "what is",
    "where can i",
    "支持吗",
    "怎么用",
    "如何",
    "是否支持",
    "说明",
    "能力边界",
    "配置说明",
)

KNOWLEDGE_REQUEST_CAPABILITY_KEYWORDS: tuple[str, ...] = (
    "feature",
    "features",
    "capability",
    "capabilities",
    "support",
    "sso",
    "integration",
    "api",
    "workspace",
    "功能",
    "能力",
    "集成",
    "接口",
    "文档",
    "documentation",
    "docs",
    "guide",
)

FEEDBACK_INTAKE_SIGNALS: tuple[tuple[tuple[str, ...], int, str], ...] = (
    (
        (
            "feature request",
            "suggest",
            "suggestion",
            "please add",
            "i wish",
            "feedback",
            "建议",
            "希望增加",
            "功能建议",
            "反馈",
        ),
        1,
        "The customer proposes product improvements or general feedback.",
    ),
    (
        (
            "frustrating",
            "disappointed",
            "bad experience",
            "poor experience",
            "complaint",
            "annoying",
            "不好用",
            "不满",
            "抱怨",
            "投诉",
            "体验很差",
        ),
        1,
        "The customer expresses dissatisfaction with the product experience.",
    ),
)

UNRELATED_KEYWORDS: tuple[str, ...] = (
    "seo",
    "backlink",
    "partnership",
    "sponsorship",
    "recruiting",
    "hiring",
    "job opportunity",
    "sales pitch",
    "marketing service",
    "商务合作",
    "招聘",
    "推广",
    "外链",
    "海外 seo",
)

FEATURE_REQUEST_KEYWORDS: tuple[str, ...] = (
    "feature request",
    "suggest",
    "suggestion",
    "please add",
    "希望增加",
    "功能建议",
    "新增功能",
)

COMPLAINT_KEYWORDS: tuple[str, ...] = (
    "frustrating",
    "disappointed",
    "complaint",
    "annoying",
    "bad experience",
    "不好用",
    "不满",
    "投诉",
    "多扣费",
)

BILLING_QUESTION_KEYWORDS: tuple[str, ...] = (
    "bill",
    "billing",
    "invoice",
    "charge",
    "charged",
    "payment",
    "账单",
    "计费",
    "收费",
    "扣费",
    "多扣费",
    "重复扣费",
)

REFUND_REQUEST_KEYWORDS: tuple[str, ...] = (
    "refund",
    "refunds",
    "chargeback",
    "退款",
    "退费",
    "撤销扣款",
)

CLARIFICATION_REPRODUCTION_KEYWORDS: tuple[str, ...] = (
    "steps to reproduce",
    "step 1",
    "step 2",
    "after i",
    "when i",
    "i clicked",
    "i configured",
    "configured",
    "followed",
    "i tried",
    "步骤",
    "我点击",
    "我配置",
    "我尝试",
    "然后",
)

CLARIFICATION_ERROR_KEYWORDS: tuple[str, ...] = (
    "error",
    "failed",
    "failure",
    "cannot",
    "can't",
    "unable",
    "timeout",
    "exception",
    "报错",
    "失败",
    "异常",
    "无法",
    "不能",
    "超时",
)

CLARIFICATION_EXPECTED_ACTUAL_KEYWORDS: tuple[str, ...] = (
    "expected",
    "instead",
    "but",
    "should",
    "supposed to",
    "预期",
    "实际",
    "本应",
    "结果",
)

CLARIFICATION_ENVIRONMENT_KEYWORDS: tuple[str, ...] = (
    "tenant",
    "workspace",
    "project",
    "account",
    "environment",
    "browser",
    "region",
    "org",
    "租户",
    "工作区",
    "项目",
    "账号",
    "环境",
    "浏览器",
    "组织",
)

ESCALATION_DISPUTED_CHARGE_KEYWORDS: tuple[str, ...] = (
    "duplicate charge",
    "charged twice",
    "charged me twice",
    "重复扣费",
    "多扣费",
)

ESCALATION_HIGH_RISK_KEYWORDS: tuple[str, ...] = (
    "sla",
    "compensation",
    "security incident",
    "security breach",
    "data loss",
    "legal",
    "contract",
    "补偿",
    "安全事故",
    "数据丢失",
    "法律",
    "合同",
)

PRIORITY_CRITICAL_KEYWORDS: tuple[str, ...] = (
    "security incident",
    "security breach",
    "data loss",
    "legal",
    "contract",
    "sla",
    "refund amount",
    "安全事故",
    "数据丢失",
    "法律",
    "合同",
    "退款金额",
)

PRIORITY_PRODUCTION_DOWN_KEYWORDS: tuple[str, ...] = (
    "production down",
    "prod down",
    "outage",
    "service unavailable",
    "生产不可用",
    "线上不可用",
)

PRIORITY_DATA_LOSS_KEYWORDS: tuple[str, ...] = (
    "data loss",
    "lost data",
    "数据丢失",
    "数据没了",
)
